### PR TITLE
scene: Only stop LEDs for running scenes.

### PR DESCRIPTION
**Pull request by aperfectring**
Signed-off-by: Joe Stefek <jstefek@datto.com>

### CODE REVIEW

**Comment by ynezz** [comment]
@aperfectring Can you provide more details in your commit description? I don't see what is wrong currently and what are you trying to fix.

**Comment by aperfectring** [comment]
@ynezz Please let me know if the details I provided are sufficient.

**Comment by ynezz** [comment]
> e.g.
Scene 1 is a "fast blink", and scene 2 is a "slow blink".  Scene 2 is paused
and scene 1 is running.  If stoping scene 2 so it won't be active when scene 1
ends: before this fix the LED will stop blinking, after it the LED will
continue blinking the "fast blink".

@aperfectring So this is related to the shared LED between those two scenes? If so, then I think, that the proper fix would be something like this:

```patch
diff --git a/scene.c b/scene.c
index 2fed597978d5..52d41a5eb1f7 100644
--- a/scene.c
+++ b/scene.c
@@ -110,9 +110,11 @@ stop_scene(struct scene *s)
 }
 
 static void
-pause_scene(struct scene *s, struct scene *paused_by)
+pause_scene(struct scene *s, struct scene *paused_by, bool stop_leds)
 {
-	stop_scene_leds(s);
+	if (stop_leds)
+		stop_scene_leds(s);
+
 	s->paused_by = paused_by;
 	set_scene_state(s, SCENE_PAUSED);
 	led_timer_cancel(&s->timer);
@@ -149,11 +151,11 @@ check_scene_priority(struct scene *run)
 				DEBUG(3, "pausing %s (prio=%d) < %s (prio=%d)\n",
 				      run->name, run->priority, cur->name,
 				      cur->priority);
-				pause_scene(run, cur);
+				pause_scene(run, cur, false);
 				return false;
 			}
 
-			pause_scene(cur, run);
+			pause_scene(cur, run, true);
 		}
 	}
```

**Comment by aperfectring** [comment]
@ynezz I found it when the "scene" ubus method is called with start = false for a scene which is either paused or already stopped (the caller isn't necessarily maintaining the state of the LEDs).  I chose to put it in the "stop_scene_leds" function because there might be other situations I couldn't think of where the condition could occur.  If the scene itself isn't running, then the LED timers weren't started by that scene, and shouldn't be modified when stopping it.

**Comment by aperfectring** [comment]
And yes, this is about shared LED(s) between those two scenes.

**Comment by ynezz** [comment]
>  I found it when the "scene" ubus method is called with start = false for a scene which is either paused or already stopped (the caller isn't necessarily maintaining the state of the LEDs).

Then from my POV it should be handled at the proper place:

```diff
> @@ -267,7 +269,9 @@ scene_stop(const char *name)
        if (!new)
                return false;
 
-       stop_scene(new);
+       if (is_running(new))
+               stop_scene(new);
+
        resume_paused_scenes(new);
        return true;
 }
```

> I chose to put it in the "stop_scene_leds" function because there might be other situations I couldn't think of where the condition could occur.

From my POV it doesn't belong there, the caller should handle the preconditions at proper place.

**Comment by aperfectring** [comment]
Stopped and !is_running are different conditions, so putting the check there is insufficient because calling scene_stop on a paused scene will leave it in the paused state.

State: S1 is paused (by S2), S2 is running
Action: stop_scene(S1)
State (with that code): S1 is paused (by S2), S2 is running
Actual state it should be in: S1 is idle, S2 is running

The same occurs with putting the check within the if (run->priority < cur->priority) mentioned earlier.  The scene being paused might never have actually been active.

State: S1 is idle, S2 is running, both scenes share an LED and S2 is higher priority.
Action: scene_run(S1)
Call chain: scene_run(S1) -> run_scene(S1) -> check_scene_priority(S1) -> pause_scene(S1, S2) -> stop_scene_leds(S1)

The only places stop_scene_leds is called is from stop_scene and pause_scene.  There are cases for both of those functions where we want to call them to ensure set_scene_state() is called appropriately (and paused_by is set appropriately for pause_scene), but stopping the LEDs isn't appropriate.

So from my point of view, we have 3 options (1 is my most desired, 3 my least desired):
1. Make the change in one place, stop_scene_leds
2. Make the change in two places, which is every place stop_scene_leds is called
3. Remove the stop_scene and pause_scene functions, and duplicate the necessary parts of that code every place those are called from.

Please let me know your preference (or provide an alternative), and I will implement that.

**Comment by ynezz** [comment]
Thanks.

**Pull request merged**
